/* Define Action Types for Shifts */
export const NEW_SHIFT_ENTRY = 'NEW_SHIFT_ENTRY';
export const SHIFT_LIST = 'SHIFT_LIST';
export const SHIFT_LIST_PENDING = 'SHIFT_LIST_PENDING';
export const SHIFT_LIST_FULFILLED = 'SHIFT_LIST_FULFILLED';
export const SHIFT_LIST_REJECTED = 'SHIFT_LIST_REJECTED';
export const UPDATE_SHIFT_ENTRY = 'UPDATE_SHIFT_ENTRY';
export const DELETE_SHIFT_ENTRY = 'DELETE_SHIFT_ENTRY';
export const SHIFT_LIST_BY_ID = 'SHIFT_LIST_BY_ID';
